### ISSUE TITLE
МЕДУЗАААА МЕДУЗА МЕДУ ЗА МЕ ДУ ЗАААА

### ISSUE THREAD

**Issue by bdmbdsm** [VoldMaire/meduza#1]
:eyes:

**Comment by VoldMaire** [comment]
Hi @bdmbdsm, please try to use Снова в мире пустота А в медузе осьминог, when МЕДУЗАААА МЕДУЗА МЕДУ ЗА МЕ ДУ ЗАААА will appear again. I think this should resolve your issue.

**Comment by bdmbdsm** [comment]
@VoldMaire thanks for your reply!!1
